### ISSUE TITLE
Stops at configuration

### ISSUE THREAD

**Issue by sverrejb** [dan-v/dosxvpn#1]
Using the packaged binary, I am unable to complete the set up. After setting up the droplet, the process hangs at the "Configuring VPN…" step without any indication of progress.

**Comment by dan-v** [comment]
Sorry to hear you're running into issues @sverrejb. Can you provide details on which region you are launching? Also if you have time to debug the issue further, it would be interesting to see the following. 
* SSH into the deployed instance (using any key you have uploaded to digital ocean), e.g. ssh -i ~/yourprivatekey core@<deployed ip>. 
* Run 'docker ps' and there should be an container called 'dosxvpn/strongswan'. If not, run a docker ps -a and see if there is a stopped container.
* Try to get logs from container: 'docker logs dosxvpn' and paste here (removing any private information)

**Comment by sverrejb** [comment]
I have tried several regions, Amsterdam, London and New York.

Log:
```
Initializing...
Starting strongSwan 5.5.2 IPsec [starter]...
# unknown keyword 'rightsubnets'
### 1 parsing error (0 fatal) ###
00[DMN] Starting IKE charon daemon (strongSwan 5.5.2, Linux 4.11.2-coreos, x86_64)
00[CFG] attr-sql plugin: database URI not set
00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
00[CFG]   loaded ca certificate "C=CN, O=strongSwan, CN=strongSwan Root CA" from '/etc/ipsec.d/cacerts/ca.cert.pem'
00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
00[CFG] loading crls from '/etc/ipsec.d/crls'
00[CFG] loading secrets from '/etc/ipsec.secrets'
00[CFG]   loaded RSA private key from '/etc/ipsec.d/private/server.pem'
00[CFG] opening triplet file /etc/ipsec.d/triplets.dat failed: No such file or directory
00[CFG] loaded 0 RADIUS server configurations
00[CFG] HA config misses local/remote address
00[LIB] loaded plugins: charon random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp curve25519 xcbc cmac curl sqlite attr kernel-netlink resolve socket-default farp stroke vici updown eap-identity eap-sim eap-aka eap-aka-3gpp2 eap-simaka-pseudonym eap-simaka-reauth eap-md5 eap-mschapv2 eap-radius eap-tls xauth-generic xauth-eap dhcp unity
charon (66) started after 40 ms
00[LIB] dropped capabilities, running as uid 100, gid 101
00[JOB] spawning 16 worker threads
03[NET] waiting for data on sockets
05[CFG] received stroke: add connection 'IPSec-IKEv2'
05[CFG] conn IPSec-IKEv2
05[CFG]   left=%any
05[CFG]   leftsubnet=0.0.0.0/0
05[CFG]   leftauth=pubkey
05[CFG]   leftid=45.55.241.144
05[CFG]   leftcert=server.cert.pem
05[CFG]   leftca=ca.cert.pem
05[CFG]   right=%any
05[CFG]   rightsourceip=10.20.30.0/24
05[CFG]   rightdns=8.8.8.8,8.8.4.4
05[CFG]   rightauth=pubkey
05[CFG]   rightid=client@45.55.241.144
05[CFG]   rightcert=client.cert.pem
05[CFG]   ike=aes256-sha256-modp1024,3des-sha1-modp1024,aes256-sha1-modp1024!
05[CFG]   esp=aes256-sha256,3des-sha1,aes256-sha1!
05[CFG]   dpddelay=300
05[CFG]   dpdtimeout=150
05[CFG]   dpdaction=1
05[CFG]   mediation=no
05[CFG]   keyexchange=ikev2
05[CFG] adding virtual IP address pool 10.20.30.0/24
05[CFG]   loaded certificate "C=CN, O=strongSwan, CN=45.55.241.144" from 'server.cert.pem'
05[CFG] CA certificate "ca.cert.pem" not found, discarding CA constraint
```

**Comment by dan-v** [comment]
Hmm I don't see anything particularly wrong in that output. Looks like the VPN launched successfully. I'm not able to reproduce your issue unfortunately - created a VPN in just about every region.

One more potential source of debugging would be to open the web browser console (right click->inspect) and during the failing step see if there is anything printed to console.

Is it always getting stuck on this step - "Configuring VPN…"? Basically during this step it's just running this command:

```
until docker logs dosxvpn &>/dev/null; do sleep 2; done; sleep 5; docker exec dosxvpn cat /etc/ipsec.d/client.mobileconfig
```

Seems like that is successful though as you were able to paste the logs to me, but could be a timing issue as using sleep here is far from a reliable method.

**Comment by sverrejb** [comment]
I tested version 0.0.3, it still stops at "Configuring VPN…". During this step the JavaScript console constantly prints 
`Object {status: "open static/dosxvpn.mobileconfig: read-only file system", ip_address: "146.185.167.132", initial_ip: "129.241.230.223", final_ip: ""}` from progress_bar.js:27

I have also tried using Firefox and Safari without any luck. Watching the scree more closely I notice that the progress bar stops for a bit, the resets/"snaps back" before it is finished. Not sure if this is relevant. If there is anything else I can do to debug let me know.

**Comment by dan-v** [comment]
Thanks @sverrejb! That's super helpful. Looks like for whatever reason the app is read-only on your system. I probably shouldn't be trying to write inside of the app anyways, so I've pushed a new version (https://github.com/dan-v/dosxvpn/releases/download/0.0.4/dosxvpn-0.0.4-osx.app.zip) that just writes to temp folder. Let me know if that solves the issue for you.

**Comment by sverrejb** [comment]
Yeah, this worked like a charm. Great work!
