### ISSUE TITLE
android install almost works. Asking for password.

### ISSUE THREAD

**Issue by gedw99** [dan-v/dosxvpn#10]
I first setup the Server using:

````
./dosxvpn deploy --region ams1 --auto-configure 

````
It works on OSX and IOS.

Now for Android i hit a little problem:
1. i installed the StrongSwan client app into Android.
2. Then I emailed the android.sswan file to myself as an attachment.
3. Then i opened the email and saved the attachment.
4. Then in the StrongSwan app i "imported the vpn profile" choosing the downloaded "android.sswan".

But i get this dialog in strong swan app GUI:
"
Extract from the Certificate for dosxvpn-xxx-ams1. Enter the password to extract the certificate
"

When i setup the server using the cli i did not see anything about password.

https://wiki.strongswan.org/projects/strongswan/wiki/AndroidVPNClientProfiles
- no hints here about password.

Any ideas ??

**Comment by dan-v** [comment]
hey @gedw99 - on the CLI it should have dumped the passphrase to output. 
```
...
Client Private Key Passphrase: LPSG8WJlPbJrUwjfLC64KHwlu8t4TAl0
...
```

**Comment by gedw99** [comment]
thanks.
i installed on my nexus 5x with the strong vpn software.
But i could not get the VPN activation button to show up.
I think its missing some extra meta data in the config file i suspect. Really guessing though.

anyone else got this working on android ?

either that or strong swan has an issue with latest andrioid.

looking around ...

**Comment by dan-v** [comment]
@gedw99 - what version of android are you running?

I have an original pixel on Android 8.x and I'm able to import the config after providing the passphrase - it takes a while to extract and I'm guessing would probably take longer on an older phone (just spins for a while). You should eventually end up getting to a prompt that says 'Name the certificate'->Select it->Click IMPORT.

**Comment by gedw99** [comment]
8.1.0 of Android 

thats what i did too. exactly the same. But i cant use the installed VPN profile. If i go to android setting > Network and Internet > VPN, there is nothing there. And from the StrongSwan VPn app i can turn it on either. Stumped !!!

i recorded it: https://youtu.be/vE5PwX_0f78

Can you see if there is something i am missing ????

**Comment by dan-v** [comment]
@gedw99 - that looks right up until the end. I get that 'edit'/'delete' menu only when i click and hold on the VPN entry. If I just click on the VPN entry it connects.

**Comment by gedw99** [comment]
dooooh. such an obvious UX thing - I guess i am am a trained pavlova dog used to Material Design cues :) 
SO it works... 

I am going to raise another issue about pi-hole.. 
Anyway thanks for bearing with me..
