### ISSUE TITLE
pihole is being an ahole

### ISSUE THREAD

**Issue by gedw99** [dan-v/dosxvpn#13]
On android
open google play and search for an app using a search term such as "speed test"
It hangs, forever !

Anyone else getting this ?

I think its because google is pumping ads in the result set.
I noticed some behaviour where is pi-hole blocks an ad, it holds up the whole page.
This is what might be happening in this case inside google play. Not sure.

Not sure also what alternatives to pi.hole we have to better handle the situation of an add being on a https page.. At the mo it seems to block the whole page

**Comment by dan-v** [comment]
I don't appear to have any issues with Pihole blocking play store by default. Once connected to VPN, you can verify what Pihole is doing by going to http://pi.hole/admin/queries.php and logging in (password is dosxvpn).

**Comment by gedw99** [comment]
i reckon there ae some good golang replacements where we might get more control.

https://github.com/drbig/adhole

https://github.com/pmezard/adblock

https://golanglibs.com/top?q=adblock
- ah its the ground Hog link...

**Comment by dan-v** [comment]
Pihole is configurable, actively maintained and provides a simple UI to block/unblock sites. Likely not going to switch this out unless there was some compelling alternative.

**Comment by gedw99** [comment]
i see your point, and yes i dont want to change it out either.

As i use the vpn i am seeing certain things we might need to change with pihole then.
1. on android, youtube does not load. I am assuming that the issue is that  ads are trying to be delivered, but they dont and it stalls the non as being delivered.

**Comment by dan-v** [comment]
Hmm.. I don't have any issues with youtube not loading on my android. If something is being blocked though you should be able to see it in the pihole interface and optionally allow it.

**Comment by gedw99** [comment]
my mistake !

youtube an google play work fine.
It was my crapping router playing up. sorry..

closing...
