### ISSUE TITLE
[Help] Allow another port

### ISSUE THREAD

**Issue by phamviet** [dan-v/dosxvpn#21]
Hello,

I do not have much experience on iptables. I want to allow access to port 3000 publicly. But below rule was not worked.

> -A INPUT -p tcp --dport 3000  -j ACCEPT

Can you help with a correct rule?
Thanks!

**Comment by dan-v** [comment]
@phamviet - there is also a digital ocean firewall that blocks traffic that gets created as part of this deployment. You can login and find it here: https://cloud.digitalocean.com/networking/firewalls. You'll need edit the firewall and add a rule for that port.

**Comment by phamviet** [comment]
Excellent! This is my bad.

Thanks @dan-v!

**Comment by dan-v** [comment]
No worries @phamviet ! Hope it works well for you.
