### ISSUE TITLE
Is there a way to convert .mobileconfig to be used on other non-macOS devices?

### ISSUE THREAD

**Issue by queuebit** [dan-v/dosxvpn#3]
I was looking into how to extract the certs in `.mobileconfig` file to no avail, and just wondered if you had ran into this and had any insight.

Thanks.

**Comment by dan-v** [comment]
### Option 1
The mobileconfig just has the cert data base64 encoded, so decoding should be all that's necessary. To use the client cert somewhere else you'll also need to have the auto generated password as well. Here's an example of getting this data out of the mobileconfig file (using a cli tool xmllint).
```
echo -n "Client cert password: " && echo "cat /plist/dict/array/dict[1]/string[1]/text()" | xmllint --nocdata --shell dosxvpn.mobileconfig | sed '1d;$d'
echo -n "Client cert saved to file: dosxvpn.client.cert.p12\n" && echo "cat /plist/dict/array/dict[1]/data/text()" | xmllint --nocdata --shell dosxvpn.mobileconfig | sed '1d;$d' | base64 -D > dosxvpn.client.cert.p12
echo -n "CA cert saved to file: dosxvpn.ca.cert.pem\n" && echo "cat /plist/dict/array/dict[2]/data/text()" | xmllint --nocdata --shell dosxvpn.mobileconfig | sed '1d;$d' | base64 -D > dosxvpn.ca.cert.pem
echo -n "Server cert saved to file: dosxvpn.server.cert.pem\n" && echo "cat /plist/dict/array/dict[4]/data/text()" | xmllint --nocdata --shell dosxvpn.mobileconfig | sed '1d;$d' | base64 -D > dosxvpn.server.cert.pem
```

### Option 2
SSH to the host and grab the files from docker container.
```
ssh -i <digital-ocean-ssh-key> core@<vpn-droplet-ip>
docker exec dosxvpn cat /etc/ipsec.d/client.cert.p12 > dosxvpn.client.cert.p12
docker exec dosxvpn cat /etc/ipsec.d/cacerts/ca.cert.pem > dosxvpn.ca.cert.pem
docker exec dosxvpn cat /etc/ipsec.d/certs/server.cert.pem > dosxvpn.server.cert.pem
```

**Comment by helxsz** [comment]
@dan-v it works for my mac. but I wonder any ubuntu based client could use the certificate to link the VPN?

**Comment by dan-v** [comment]
@helxsz - Yeah, you should definitely be able to use these certs on other platforms. Take a look at strongswan client (https://strongswan.org/). I've used these exported certificates with the Android strongswan client without any issues.

**Comment by helxsz** [comment]
![screen shot 2017-10-11 at 14 59 04](https://user-images.githubusercontent.com/669670/31446747-26a6607a-ae98-11e7-9752-1a651ec78828.png)

I tried this but still failed for some reason.

**Comment by dan-v** [comment]
@helxsz - There's a good thread over on algo issues page (much of the strongswan config was borrowed from this project): https://github.com/trailofbits/algo/issues/263. There appears to be some potential issues to work around on Ubuntu. Looks like you may need Network Manager 1.4.2+ and possibly need to modify the list of cipher suites set on server side. Right now the cipher config looks like this: https://github.com/dosxvpn/strongswan/blob/master/Dockerfile#L15. Let me know if you figure it out. I'd be willing to make changes to optionally add additional ciphers if you wanted to share the vpn across platforms.

**Comment by helxsz** [comment]
@dan-v h, thanks, i will try network manager 1.4.2+, and I have also shared the key with you through email

**Comment by z362194037** [comment]
Excuse me ！How do I upgrade NetworkManager?

**Comment by dan-v** [comment]
@z362194037 - if your package manager doesn't have this version then you probably need to build from source unfortunately. See this page as an example: https://wiki.strongswan.org/projects/strongswan/wiki/NetworkManager#Installation. Note: I haven't actually tried this, so not sure that it works.

**Comment by helxsz** [comment]
@dan-v one question, for dosxvpn.ca.cert.pem,dosxvpn.client.cert.p12, dosxvpn.server.cert.pem, I am confused about what they are exactly as the server certificate, client certificate and client secret, can you point out to me please?

**Comment by dan-v** [comment]
@helxsz - sorry for delayed response on this.

- dosxvpn.ca.cert.pem - this is the root CA certificate used to generate all other certificates
- dosxvpn.server.cert.pem - this is the generated certificate used by the VPN server
- dosxvpn.client.cert.p12 - this is the generated client key/cert in p12 format. A p12 file contains the private key, its certificate, and the certificate of the server (dosxvpn.server.cert.pem).

**Comment by dan-v** [comment]
Newer versions of dosxvpn now dump all of these files to ~/.dosxvpn directory.
