### ISSUE TITLE
how would I login to the server?

### ISSUE THREAD

**Issue by helxsz** [dan-v/dosxvpn#4]
I tried to login into the digitalocean through ssh root@ip, but showing Permission denied (publickey).
I have the publickey shared in both two places. 

Any ideas ?

**Comment by dan-v** [comment]
Give this a shot:
ssh -i \<digital-ocean-ssh-key> core@\<vpn-droplet-ip>

**Comment by JosephShenton** [comment]
where do i find the ssh key if i used the web gui?
