### ISSUE TITLE
Error when creating a new droplet

### ISSUE THREAD

**Issue by stv8** [dan-v/dosxvpn#5]
After I run `$ ./dosxvpn deploy --region sfo2 --auto-configure` I get an error 

```2017/11/05 11:38:44 POST https://api.digitalocean.com/v2/droplets: 422 The image for this droplet does not use root passwords, please use an SSH key.```

I have my access token set, but it appears to fail creating the droplet and VPN.

**Comment by dan-v** [comment]
Thanks for reporting this issue @stv8 . I was able to reproduce it by not having an SSH key in my DigitalOcean account, which is something I haven't accounted for. I'll have to figure out how I want to handle this situation. For now, you should be able to add an SSH key here: https://cloud.digitalocean.com/settings/security and then be able to deploy.

**Comment by stv8** [comment]
Ok, it was able to create the droplet, configure the vpn, and add the profile to my network settings. However I can't reach any sites whenever I connect to the vpn. Every website hangs.

**Comment by dan-v** [comment]
Sorry to hear that @stv8 . Just to clarify, the VPN does actually connect successfully and stay connected but you can't pass traffic? 

If you have time to help debug here are some potential ideas:
* Does ping work when connected: `ping 8.8.8.8`
* What is your nameserver set to on OSX when connected: `cat /etc/resolv.conf`
* Can you get to this address in your browser: http://1.1.1.1/admin/
* What does your routing table look like when connected (there should be a default route with ipsec interface): `netstat -nr`
* What is your initial home subnet you are connecting from (e.g. 192.168.1.0)? If it was overlapping with the assigned 10.30.20.0/24 subnet this could cause issues.
* SSH into the instance and copy the output from dosxvpn container:
** `ssh -i <your key> core@<vpn ip>`
**  `docker logs dosxvpn`

**Comment by stv8** [comment]
@dan-v yeah sure thing, I can help debug in a little bit thanks for the response. 

As a follow up question though, I noticed that dosxvpn needs my ssh key, (I'm assuming to provision the server), how do I know that it is grabbing the correct ssh key and not combing through my other private keys?

**Comment by dan-v** [comment]
dosxvpn only queries your public SSH keys on DigitalOcean and adds all of them as authorized keys to login to the droplet. It doesn't touch any of your local filesystem keys.

**Comment by dan-v** [comment]
Also, an SSH key is actually generated in memory for the deployment process but the private key is not saved and is lost as soon as the program exits. The need for a public key is due to DigitalOcean requiring it for droplet creation specifically with the CoreOS image (doesn't support password auth), but is still useful as it gives you access to the droplet after creation.

**Comment by stv8** [comment]
@dan-v I created another instance and it is working now. Maybe the installation wasn't fully complete the first time. Thanks for the helpful debugging steps and the informational responses 👍

**Comment by dan-v** [comment]
Awesome, glad you got it up and running @stv8 !
