### ISSUE TITLE
My .mobileconfig stopped working about a week ago

### ISSUE THREAD

**Issue by queuebit** [dan-v/dosxvpn#8]
About a week ago when I try to connect on MacOS 10.11.6 using the `.mobileconfig` file, it seems to connect but then I lose internet connection on my machine.

Digital Ocean still seems to be working, but I can't seem to access the VPN, or the internet after configuring and connecting using the `.mobileconfig` settings.

Anyone else seeing this too?

**Comment by dan-v** [comment]
Hey @queuebit . I'm guessing that I probably screwed things up with the latest update which made a few changes that could impact someone running an older version. These changes included a move from RSA to ECDSA keys and change of VPN subnet from 10.x.x.x to 192.168.99.x). Unfortunately, I haven't been doing a very good job at maintaining backwards compatibility. If you could grab the latest version of dosxvpn and redeploy - let me know if that resolves the problem.

**Comment by queuebit** [comment]
I installed `0.9` release, removed old VPN, and downloaded new Apple `.mobileconfig` settings.

When I try to connect using `dosxvpn.apple.mobileconfig`, I get the following error:
<img width="663" alt="screen shot 2017-11-20 at 4 04 01 pm" src="https://user-images.githubusercontent.com/945262/33041530-a35f68da-ce0c-11e7-98f9-ac07971671c1.png">

I am running `10.11.6`

**Comment by queuebit** [comment]
This time I tried to deploy using cli.

Here is the logged error when trying to configure the VPN:

```
2017/11/28 10:01:56 VPN is now active...
2017/11/28 10:01:56 Getting/generating VPN files...
2017/11/28 10:02:02 Finished getting/generating VPN files...
2017/11/28 10:02:02 Adding VPN to OSX...
2017/11/28 10:02:02 Failed to add VPN to OSX. Failed to add VPN. Output: profiles unable to read in dictionary at file '/Users/<>/.dosxvpn/dosxvpn-640-sfo2.apple.mobileconfig', or via stdin
profiles install for file:'/Users/<>/.dosxvpn/dosxvpn-640-sfo2.apple.mobileconfig' and user:'<>' returned -4599 (The operation couldn’t be completed. (OSStatus error -4599.))
. Error: exit status 1
```

**Comment by dan-v** [comment]
I'll try to take a look at this soon @queuebit . I'm guessing it's an OSX version difference.

**Comment by dan-v** [comment]
@queuebit - Rather than trying to maintain backwards compatibility with older version of OSX, I just created a new branch and release with previous version of code and docker container: https://github.com/dan-v/dosxvpn/releases/tag/legacy. Let me know if that works for you.

**Comment by queuebit** [comment]
I grabbed the legacy cli Release.

It just keeps hanging on `Connecting...` in the network panel and I don't have access to web.

<img width="603" alt="connecting_" src="https://user-images.githubusercontent.com/945262/33457018-286456a0-d5ef-11e7-8589-c14b2078aa15.png">

Is there a way for me to grab logs to see what is actually happening? I don't want you to spend too much time handling my case though either. Are you on Sierra or High Sierra?

cli logs seem normal:
```
Downloads $ ./dosxvpn deploy --region sfo2 --auto-configure

___  ____ ____ _  _ _  _ ___  _  _ 
|  \ |  | [__   \/  |  | |__] |\ | 
|__/ |__| ___] _/\_  \/  |    | \| 


2017/11/30 16:48:23 Getting initial IP...
2017/11/30 16:48:24 Initial IP is: xxx.xx.xx.xxxx
2017/11/30 16:48:24 Getting account SSH keys...
2017/11/30 16:48:25 Finished getting account SSH keys...
2017/11/30 16:48:25 Creating droplet...
2017/11/30 16:48:26 Finished creating droplet dosxvpn-xxx-sfo2
2017/11/30 16:48:26 Waiting for droplet to get IP...
2017/11/30 16:48:28 Droplet now has IP xxx.xx.xx.xx...
2017/11/30 16:48:28 Creating firewall...
2017/11/30 16:48:41 Finished creating firewall...
2017/11/30 16:48:41 Waiting for SSH to start...
2017/11/30 16:49:16 SSH is now online...
2017/11/30 16:49:16 Waiting for VPN to become active...
2017/11/30 16:49:29 VPN is now active...
2017/11/30 16:49:29 Getting/generating VPN files...
2017/11/30 16:49:32 Finished getting/generating VPN files...
2017/11/30 16:49:32 Adding VPN to OSX...
2017/11/30 16:49:38 Done Adding VPN to OSX...
2017/11/30 16:50:28 ##############################
...
```

**Comment by dan-v** [comment]
@queuebit - getting logs from server side would be helpful. Here is how you could do that. SSH into the instance and copy the output from dosxvpn container:
** `ssh -i <your key> core@<vpn ip>`
**  `docker logs dosxvpn`

I am on Sierra currently, but happy to help as much as I can to debug your issue further.

**Comment by queuebit** [comment]
```
Container Linux by CoreOS beta (1576.3.0)
core@dosxvpn-xxx-sfo2 ~ $ docker logs dosxvpn
VPN has already been setup!
Starting strongSwan 5.6.0 IPsec [starter]...
# unknown keyword 'rightsubnets'
### 1 parsing error (0 fatal) ###
00[DMN] Starting IKE charon daemon (strongSwan 5.6.0, Linux 4.13.16-coreos-r1, x86_64)
00[KNL] known interfaces and IP addresses:
00[KNL]   lo
00[KNL]     127.0.0.1
00[KNL]     ::1
00[KNL]   eth0
00[KNL]     xxx.xx.xx.xx
00[KNL]     xx.xx.x.x
00[KNL]     xxxx:xxxx:0:yy::yy:xxxx
00[KNL]     xxxx:xxxx:0:yy::yy:xxxx
00[KNL]   dummy0
00[KNL]     1.1.1.1
00[KNL]     xxxx:xxxx:0:yy::yy:xxxx
00[KNL]   docker0
00[KNL]     172.xx.0.1
00[CFG] attr-sql plugin: database URI not set
00[CFG] loading ca certificates from '/etc/ipsec.d/cacerts'
00[CFG]   loaded ca certificate "C=CN, O=strongSwan, CN=strongSwan Root CA" from '/etc/ipsec.d/cacerts/ca.cert.pem'
00[CFG] loading aa certificates from '/etc/ipsec.d/aacerts'
00[CFG] loading ocsp signer certificates from '/etc/ipsec.d/ocspcerts'
00[CFG] loading attribute certificates from '/etc/ipsec.d/acerts'
00[CFG] loading crls from '/etc/ipsec.d/crls'
00[CFG] loading secrets from '/etc/ipsec.secrets'
00[CFG]   loaded ECDSA private key from '/etc/ipsec.d/private/server.pem'
00[CFG] read 0 triplets from /etc/ipsec.d/triplets.dat
00[CFG] loaded 0 RADIUS server configurations
charon (21) started after 100 ms
00[CFG] HA config misses local/remote address
00[LIB] loaded plugins: charon random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp curve25519 xcbc cmac curl sqlite attr kernel-netlink resolve socket-default farp stroke vici updown eap-identity eap-sim eap-sim-file eap-aka eap-aka-3gpp2 eap-simaka-pseudonym eap-simaka-reauth eap-md5 eap-mschapv2 eap-radius eap-tls xauth-generic xauth-eap dhcp unity
00[LIB] dropped capabilities, running as uid 100, gid 101
00[JOB] spawning 16 worker threads
03[NET] waiting for data on sockets
05[CFG] received stroke: add connection 'ikev2-pubkey'
05[CFG] conn ikev2-pubkey
05[CFG]   left=%any
05[CFG]   leftsubnet=0.0.0.0/0,::/0
05[CFG]   leftauth=pubkey
05[CFG]   leftid=xxx.xx.xx.xx
05[CFG]   leftcert=server.cert.pem
05[CFG]   right=%any
05[CFG]   rightsourceip=192.168.xx.0/24,xxx:yy:xx:yy/24
05[CFG]   rightdns=1.1.1.1
05[CFG]   rightauth=pubkey
05[CFG]   ike=aes128gcm16-prfsha512-ecp256!
05[CFG]   esp=aes128gcm16-ecp256!
```

**Comment by dan-v** [comment]
@queuebit - Looks like my automated build setup in CircleCI ended up building master branch instead of legacy branch so I uploaded the wrong binaries. Also found another issue where config wasn't being properly generated due to missing commit on legacy docker image branch (https://github.com/dosxvpn/strongswan/tree/legacy). Re-uploaded here: https://github.com/dan-v/dosxvpn/releases/tag/legacy. Let me know if that works for you.

**Comment by queuebit** [comment]
That's a winner.

Thanks for all the help. I will test it out over the next week or so, but will close this for now.

Thanks, Dan!
