### ISSUE TITLE
Loses internet connection after creating droplet and added .mobileconfig to Mac

### ISSUE THREAD

**Issue by georgeperez** [dan-v/dosxvpn#9]
Currently provisioning a dosxvpn. The droplet deploys fine on DigitalOcean but once it auto-adds the `mobileconfig` file to macOS, it stops the internet connection. Since it stops the internet connection, it never finished setting up and I'm not presented with the option to download the `mobileconfig` files for iOS or to modify the ad block settings. Once I disable the VPN, the internet connection comes back online.

I'm running macOS High Sierra 10.13.2 at the moment. Any idea what's happening?

**Comment by dan-v** [comment]
@georgeperez  - what version of dosxvpn are you running? 

I haven't upgraded yet to High Sierra, so I'm not certain that it works yet. I'll probably get around to doing that soon. Unfortunately it's a bit of a pain to debug dosxvpn at the moment. The most useful information would be on the droplet itself, so SSH into it and look at the logs for the container running there.
** ssh -i <your key> core@<vpn ip>
** docker logs dosxvpn

**Comment by georgeperez** [comment]
I think High Sierra might be the issue. I'm getting errors in the CLI version that it couldn't add the macOS profile because the ~/.dosxvpn directory was "read-only", and with the web version it "succeeds" at adding the profile but it loses an internet connection. I'll try re-running it with the web version and showing grabbing the logs.

**Comment by gedw99** [comment]
i am on the same OSX version, and run and it worked first time.
server up, vpn installed and showing in taskbar

````
	chmod +x dosxvpn
	./dosxvpn deploy --region ams2 --auto-configure 

````
